fix(facebook): only send `event_params` if present
Streaming from Go Live without an scheduled event causes `OAuth
Exception: (#100) Broadcast does not associate with a Live Online Event"
when calling update endpoint on Facebook API. Their docs mention these
are "Parameters specific to Live Online Event broadcast.".

Assuming the fetch works correctly for such cases we can rely on whether
any of it's info is set to check whether we should send it to the update
endpoint.

ref: https://app.asana.com/0/734380881425048/1204374502675060/f