Big refactor: clean TSLint + AirBnB config (#1129)
* refactor: fix code issues, details follow

These are some, but not all, of the changes:

* add lint commands, including CI, to `package.json`.
* remove eslint, we will invest on tslint instead.
* add `readonly` modifier to fields that deserve it.
* shorten imports.
* fix chatbot templates having invalid syntax.
* add AirBnB config through tslint and apply automatic fixes.
* manual fixes.

* test: import `reflect-metadata` in services manager

Perhaps related to compilation order, `reflect-metadata` has to be imported in this file, otherwise
we would get the following compilation error:

```
app/services-manager.ts(545,21): error TS2339: Property 'getMetadata' does not exist on type 'typeof Reflect'.
```