test: import `reflect-metadata` in services manager
Perhaps related to compilation order, `reflect-metadata` has to be imported in this file, otherwise
we would get the following compilation error:

```
app/services-manager.ts(545,21): error TS2339: Property 'getMetadata' does not exist on type 'typeof Reflect'.
```